// 389. Find the Difference
// Difficulty: Easy

// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t

// Time:  O(n)
// Space: O(1)

class Solution {
public:
  char findTheDifference(string s, string t) {
    return accumulate(s.cbegin(), s.cend(), 0, bit_xor<int>()) ^ 
           accumulate(t.cbegin(), t.cend(), 0, bit_xor<int>());
  }
};
