// 389. Find the Difference
// Difficulty: Easy
// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t

// Time:  O(n)
// Space: O(1)

#import <Foundation/Foundation.h>

char findTheDifference(NSString* s, NSString* t) {
  char result = 0;
  for (int i = 0; i < s.length; i++) {
    result ^= [s characterAtIndex:i] ^ [t characterAtIndex:i];
  }
  return result ^ [t characterAtIndex:t.length - 1];
}

